// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR4fjvVt2zj4SJQs5zkDtxz999WjpMHhU',
    appId: '1:411555203714:web:218ec44acf769fbdf5429b',
    messagingSenderId: '411555203714',
    projectId: 'finalprojectflutter-bd416',
    authDomain: 'finalprojectflutter-bd416.firebaseapp.com',
    storageBucket: 'finalprojectflutter-bd416.appspot.com',
    measurementId: 'G-3142V1EPVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcNjZrruB2VekwzG7LupCQGuvLpt45PPM',
    appId: '1:411555203714:android:bb5485b44a025e36f5429b',
    messagingSenderId: '411555203714',
    projectId: 'finalprojectflutter-bd416',
    storageBucket: 'finalprojectflutter-bd416.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzzP2BSfJh1copHNE1JdFvbhyrXoE6fxM',
    appId: '1:411555203714:ios:144d1ca8adf4755ff5429b',
    messagingSenderId: '411555203714',
    projectId: 'finalprojectflutter-bd416',
    storageBucket: 'finalprojectflutter-bd416.appspot.com',
    iosClientId: '411555203714-0ojlbsh47fjgp1385ac803uq9c246a2a.apps.googleusercontent.com',
    iosBundleId: 'com.mobr1.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzzP2BSfJh1copHNE1JdFvbhyrXoE6fxM',
    appId: '1:411555203714:ios:84eb4db0494b1450f5429b',
    messagingSenderId: '411555203714',
    projectId: 'finalprojectflutter-bd416',
    storageBucket: 'finalprojectflutter-bd416.appspot.com',
    iosClientId: '411555203714-g1cqrgiqdn5lc2hvcle8k85phofrits4.apps.googleusercontent.com',
    iosBundleId: 'com.mobr1.finalProject.RunnerTests',
  );
}
